apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-web-ui
  labels:
    app: open-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-web-ui
  template:
    metadata:
      labels:
        app: open-web-ui
    spec:
      containers:
        - name: open-web-ui
          image: ghcr.io/open-webui/open-webui:main  # Updated image reference
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "http://argued-backend-service:5000"  # Adjust this to your ArguED backend API URL
